var script = document.createElement('script');
console.log(script);
script.innerText = "var item = document.createElement('h1');";
script.innerText += "item.style['z-index'] = '999';";
script.innerText += "item.style.position = 'absolute';";
script.innerText += "item.style.color = '#FF0000';";
script.innerText += "let engine_judge = false;";
script.innerText += "let engine = [";
script.innerText += "[window.phina,'phina: ','VERSION'],";
script.innerText += "[window.Phaser,'Phaser: ','VERSION'],";
script.innerText += "[window.PIXI,'PIXI: ','VERSION'],";
script.innerText += "[window.createjs,'createjs: ','EaselJS','PreloadJS','SoundJS','TweenJS'],";
script.innerText += "[window.THREE,'THREE'],";
script.innerText += "[window.pc,'playcanvas :','version'],";
script.innerText += "[window.wwf,'wwf: ','version'],";
script.innerText += "[window.CocosEngine,'Cocos:']";
script.innerText += "];";
script.innerText += "item.innerText = '该游戏所用引擎是: ';";
script.innerText += "for (var i = 0; i < 8; i++) {";
script.innerText += "  if (engine[i][0]) { engine_judge = true;";
script.innerText += "   if (engine[1][0] && engine[2][0]) {";
script.innerText += "     item.innerText += engine[1][1] + engine[1][0][engine[1][2]] + ' '; ";
script.innerText += "     if (engine[2][0][engine[2][2]]){item.innerText += engine[2][1] + engine[2][0][engine[2][2]];}";
script.innerText += "     engine[2][0] = 0;";
script.innerText += "   }";
script.innerText += "   else if (engine[3][0]) {item.innerText += engine[3][1];";
script.innerText += "     for (var j = 2; j < engine[i].length; j++) { if(engine[3][0][engine[3][j]]){item.innerText += engine[3][j] + engine[3][0][engine[i][j]].version + ' '; }}";
script.innerText += "   }";
script.innerText += "   else if (engine[7][0]) {";
script.innerText += "     item.innerText += engine[i][1] + engine[i][0]; ";
script.innerText += "   }";
script.innerText += "   else{";
script.innerText += "     item.innerText += engine[i][1] + engine[i][0][engine[i][2]]; ";
script.innerText += "   }";
script.innerText += " }";
script.innerText += "}";
script.innerText += "if(!engine_judge){item.innerText += '其他引擎'};";
script.innerText += "document.body.insertBefore(item, document.body.firstChild);";
document.body.appendChild(script);