var script = document.createElement('script');
console.log(script);
script.innerText = "var item = document.createElement('h1');";
script.innerText += "item.style['z-index'] = '999';";
script.innerText += "item.style.position = 'absolute';";
script.innerText += "item.style.color = '#FF0000';";
script.innerText += "var engine;";
script.innerText += "if(window.phina){engine = 'phina: ' + window.phina.VERSION};";
script.innerText += "if(window.Phaser){engine = 'Phaser: ' + window.Phaser.VERSION + ' ';if(window.PIXI.VERSION){ engine += 'PIXI: ' + window.PIXI.VERSION}};";
script.innerText += "if(window.PIXI && !window.Phaser){engine = 'PIXI: ' + window.PIXI.VERSION};";
script.innerText += "if(window.createjs){engine = 'createjs\n '; if(window.createjs.EaselJS && window.createjs.PreloadJS && window.createjs.SoundJS && window.createjs.TweenJS){engine += 'EaselJS: ' + window.createjs.EaselJS.version + ', PreloadJS: ' + window.createjs.PreloadJS.version + ', SoundJS: ' + window.createjs.SoundJS.version + ', TweenJS: ' + window.createjs.TweenJS.version}};";
script.innerText += "if(window.THREE){engine = 'THREE'};";
script.innerText += "if(window.pc){engine = 'playcanvas' + window.pc.version};";
script.innerText += "if(window.wwf){engine = 'wwf' + window.wwf.version};";
script.innerText += "item.innerText ='该游戏所用引擎是' + (window.CocosEngine || engine ||'其他引擎');";
 script.innerText += "console.log('---------------',engine);";
script.innerText += "document.body.insertBefore(item, document.body.firstChild);";
document.body.appendChild(script);
